import './global.css';


export const metadata = {
    title: 'LSB portfolio by Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang={"ko"}>
            <body>
                {children}
            </body>
        </html>
    );
}